name: Run Python Script Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Toutes les 10 minutes
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python VIE_API.py  # Remplacez par le nom de votre script

      - name: Commit and Push CSV
        run: |
          git config --global user.name "Mohamed Zenati"
          git config --global user.email "z.mohamedpro@gmail.com"
          git add nom_du_fichier.csv
          git commit -m "Update CSV file with new data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
